#!/bin/bash

#TODO: (optional) make source (and target) selectable through command line arguments
source="../../MemoryCheck/test/resources"
target="../test/resources"
mkdir -p ../test
cp -r $source $target

rtrn=0
tests=test_*

if [ $1 ]
then
    tests=$*
else
    rm -f test_*.log
fi

echo $(echo -n "Running tests - " && date && echo "") > tests.log

for test in $tests; do
    rm -f $test.log
    ./$test > ${test}.log 2> ${test}_cerr.log
    test_rtrn=$?
    if [ $test_rtrn -ne 0 ]
    then
        #sums number of failed test - like it's done by the tests themselves
        let "rtrn+=$test_rtrn"
    fi
    echo $test
    cat ${test}.log >> tests.log
    cat ${test}.log | grep -E '=======|No tests ran|All tests|test cases:|assertions:'
    echo
done

rm -r $target

exit $rtrn